<?php
/**
 * credentialsFunctions.php — pasteable per-app credential collection.
 *
 * An app declares WHAT it needs in an in-repo `credentials.json` manifest
 * (generated by the builder from the spec's configuration doc). Values are
 * pasted in from nokemo (monitoring paste-in) or the provisioning wizard and
 * stored OUTSIDE the webroot under $files_location — NEVER returned to any
 * caller and never committed to git. See docs/credentials-manifest.md.
 *
 * The `secret` flag only controls display masking; secret and non-secret
 * ("setting") values share one store, so a settings screen can use
 * credential_get()/credential_set() too.
 */

/** Locate the app's credential manifest. Config may pin it; else auto-discover. */
function credential_manifest_path() {
    global $credential_manifest_file, $files_location;
    if (!empty($credential_manifest_file) && is_file($credential_manifest_file)) {
        return $credential_manifest_file;
    }
    $webroot = dirname(dirname(dirname(__DIR__))); // public_html/ (admin/ is a child)
    $candidates = [
        // public_html/credentials.json (sibling of admin/), if placed at the root.
        $webroot . '/credentials.json',
        // Staged next to the value store, above the webroot.
        (isset($files_location) ? rtrim($files_location, '/') . '/credentials.manifest.json' : ''),
    ];
    // The child app deploys to public_html/{slug}/ — pick up its manifest there
    // (skip admin/, which is core, not an app).
    foreach (glob($webroot . '/*/credentials.json') ?: [] as $g) {
        if (basename(dirname($g)) !== 'admin') { $candidates[] = $g; }
    }
    foreach ($candidates as $c) {
        if ($c !== '' && is_file($c)) { return $c; }
    }
    return '';
}

/** Parse the manifest into a normalized array of entries. Empty if none. */
function credential_manifest() {
    $p = credential_manifest_path();
    if ($p === '') { return []; }
    $raw = @file_get_contents($p);
    if ($raw === false) { return []; }
    $j = json_decode($raw, true);
    if (!is_array($j)) { return []; }
    // Accept a bare array or {"credentials": [...]}.
    $items = (isset($j['credentials']) && is_array($j['credentials'])) ? $j['credentials'] : $j;
    $out = [];
    foreach ($items as $it) {
        if (!is_array($it) || empty($it['key'])) { continue; }
        $out[] = [
            'key'      => (string)$it['key'],
            'label'    => (string)($it['label'] ?? $it['key']),
            'group'    => (string)($it['group'] ?? ($it['phase'] ?? 'General')),
            'secret'   => !empty($it['secret']),
            'required' => array_key_exists('required', $it) ? (bool)$it['required'] : true,
            'validate' => isset($it['validate']) ? (string)$it['validate'] : '',
            'howto'    => (string)($it['howto'] ?? ''),
        ];
    }
    return $out;
}

/** Value store path — outside the webroot, persists across deploys. */
function credential_store_path() {
    global $files_location;
    $dir = isset($files_location) ? rtrim($files_location, '/') : sys_get_temp_dir();
    return $dir . '/credentials.store.json';
}

function credential_store_all() {
    $p = credential_store_path();
    if (!is_file($p)) { return []; }
    $j = json_decode(@file_get_contents($p), true);
    return is_array($j) ? $j : [];
}

/** Get one stored value (or null). For app runtime use — not exposed by the API. */
function credential_get($key) {
    $all = credential_store_all();
    return array_key_exists($key, $all) ? $all[$key] : null;
}

/** Delimit a manifest regex safely (values may contain `/`). */
function credential_regex($pattern) {
    return '~' . str_replace('~', '\~', $pattern) . '~';
}

function credential_is_satisfied($entry) {
    $v = credential_get($entry['key']);
    if ($v === null || $v === '') { return false; }
    if (!empty($entry['validate']) && @preg_match(credential_regex($entry['validate']), (string)$v) !== 1) {
        return false;
    }
    return true;
}

/**
 * Manifest annotated with satisfied status. NEVER includes values.
 * This is what nokemo reads to render the "Credentials" card and to know what's
 * still missing.
 */
function credential_status() {
    $items   = credential_manifest();
    $rows    = [];
    $missing = [];
    foreach ($items as $e) {
        $sat = credential_is_satisfied($e);
        $rows[] = [
            'key'      => $e['key'],
            'label'    => $e['label'],
            'group'    => $e['group'],
            'secret'   => $e['secret'],
            'required' => $e['required'],
            'howto'    => $e['howto'],
            'satisfied'=> $sat,
        ];
        if ($e['required'] && !$sat) {
            $missing[] = [
                'key'    => $e['key'],
                'label'  => $e['label'],
                'group'  => $e['group'],
                'secret' => $e['secret'],
                'howto'  => $e['howto'],
            ];
        }
    }
    return [
        'credentials'   => $rows,
        'missing'       => $missing,
        'missing_count' => count($missing),
        'has_manifest'  => !empty($items),
    ];
}

/**
 * Validate + persist one credential value.
 * @return array [bool $ok, string $error, bool $satisfied]
 */
function credential_set($key, $value) {
    $entry = null;
    foreach (credential_manifest() as $e) {
        if ($e['key'] === $key) { $entry = $e; break; }
    }
    if ($entry === null) { return [false, 'Unknown credential key.', false]; }
    $value = (string)$value;
    if ($value === '') { return [false, 'Empty value.', false]; }
    if (!empty($entry['validate']) && @preg_match(credential_regex($entry['validate']), $value) !== 1) {
        return [false, 'Value does not match the required format.', false];
    }

    $p   = credential_store_path();
    $dir = dirname($p);
    if (!is_dir($dir)) { @mkdir($dir, 0700, true); }
    $all = credential_store_all();
    $all[$key] = $value;
    $tmp = $p . '.tmp';
    if (@file_put_contents($tmp, json_encode($all, JSON_PRETTY_PRINT), LOCK_EX) === false) {
        return [false, 'Could not write credential store.', false];
    }
    @chmod($tmp, 0600);
    if (!@rename($tmp, $p)) { @unlink($tmp); return [false, 'Could not persist credential store.', false]; }
    @chmod($p, 0600);
    return [true, '', credential_is_satisfied($entry)];
}

/** Append an audit line (who/when/key — NEVER the value). */
function credential_audit_log($key, $actor = '') {
    global $files_location;
    $dir = isset($files_location) ? rtrim($files_location, '/') : sys_get_temp_dir();
    $line = date('c') . "\tset\tkey=" . $key . ($actor !== '' ? "\tby=" . $actor : '') . "\n";
    @file_put_contents($dir . '/credentials.audit.log', $line, FILE_APPEND | LOCK_EX);
}
