<?php
/**
 * install/index.php — Wave Networks Core Installer
 * Collects database credentials, tests connections, generates secrets, writes config.php.
 * DELETE THIS DIRECTORY after installation.
 */

// Prevent running if config already exists
$configPath = __DIR__ . '/../config/config.php';
if (file_exists($configPath)) {
    // Lock down install directory if still accessible
    @chmod(__DIR__ . '/index.php', 0000);
    @chmod(__DIR__ . '/.htaccess', 0000);
    @chmod(__DIR__, 0000);
    http_response_code(403);
    exit;
}

$errors = [];
$success = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {

    // Collect values
    $dbHost       = trim($_POST['db_host'] ?? 'localhost');
    $dbName       = trim($_POST['db_name'] ?? '');
    $dbUser       = trim($_POST['db_user'] ?? '');
    $dbPass       = $_POST['db_pass'] ?? '';

    $shard1Host   = trim($_POST['shard1_host'] ?? 'localhost');
    $shard1Name   = trim($_POST['shard1_name'] ?? '');
    $shard1User   = trim($_POST['shard1_user'] ?? '');
    $shard1Pass   = $_POST['shard1_pass'] ?? '';

    $shard2Host   = trim($_POST['shard2_host'] ?? 'localhost');
    $shard2Name   = trim($_POST['shard2_name'] ?? '');
    $shard2User   = trim($_POST['shard2_user'] ?? '');
    $shard2Pass   = $_POST['shard2_pass'] ?? '';

    $filesLoc     = rtrim(trim($_POST['files_location'] ?? ''), '/') . '/';

    $smtpHost     = trim($_POST['smtp_host'] ?? '');
    $smtpPort     = (int)($_POST['smtp_port'] ?? 587);
    $smtpUser     = trim($_POST['smtp_user'] ?? '');
    $smtpPass     = $_POST['smtp_pass'] ?? '';
    $mailFrom     = trim($_POST['mail_from'] ?? '');
    $mailFromName = trim($_POST['mail_from_name'] ?? 'Admin');

    // Validate required fields
    if (!$dbName) $errors[] = 'Main database name is required.';
    if (!$dbUser) $errors[] = 'Main database user is required.';
    if (!$shard1Name) $errors[] = 'Shard 1 database name is required.';
    if (!$shard2Name) $errors[] = 'Shard 2 database name is required.';
    if (!$filesLoc || $filesLoc === '/') $errors[] = 'Files directory path is required.';

    // Test DB connections
    if (empty($errors)) {
        // Main DB
        try {
            $pdo = new PDO("mysql:host=$dbHost;dbname=$dbName;charset=utf8mb4", $dbUser, $dbPass);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            $pdo = null;
        } catch (PDOException $e) {
            $errors[] = "Main DB connection failed: " . $e->getMessage();
        }

        // Shard 1
        $s1User = $shard1User ?: $dbUser;
        $s1Pass = $shard1Pass !== '' ? $shard1Pass : $dbPass;
        try {
            $pdo = new PDO("mysql:host=$shard1Host;dbname=$shard1Name;charset=utf8mb4", $s1User, $s1Pass);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            $pdo = null;
        } catch (PDOException $e) {
            $errors[] = "Shard 1 DB connection failed: " . $e->getMessage();
        }

        // Shard 2
        $s2User = $shard2User ?: $dbUser;
        $s2Pass = $shard2Pass !== '' ? $shard2Pass : $dbPass;
        try {
            $pdo = new PDO("mysql:host=$shard2Host;dbname=$shard2Name;charset=utf8mb4", $s2User, $s2Pass);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            $pdo = null;
        } catch (PDOException $e) {
            $errors[] = "Shard 2 DB connection failed: " . $e->getMessage();
        }
    }

    // Write config.php
    if (empty($errors)) {
        $hiddenHash = bin2hex(random_bytes(32));
        $appSecret  = bin2hex(random_bytes(32));

        // Use main DB credentials as defaults for shards if not specified
        $s1UserOut = $shard1User ?: $dbUser;
        $s1PassOut = $shard1Pass !== '' ? $shard1Pass : $dbPass;
        $s2UserOut = $shard2User ?: $dbUser;
        $s2PassOut = $shard2Pass !== '' ? $shard2Pass : $dbPass;

        $config = "<?php\n";
        $config .= "// Generated by installer on " . date('Y-m-d H:i:s') . "\n\n";
        $config .= "\$dbHostSpec  = " . var_export($dbHost, true) . ";\n";
        $config .= "\$dbInstance  = " . var_export($dbName, true) . ";\n";
        $config .= "\$dbUserName  = " . var_export($dbUser, true) . ";\n";
        $config .= "\$dbPassword  = " . var_export($dbPass, true) . ";\n\n";
        $config .= "\$shardConfigs = [\n";
        $config .= "    'shard1' => [\n";
        $config .= "        'host' => " . var_export($shard1Host, true) . ",\n";
        $config .= "        'name' => " . var_export($shard1Name, true) . ",\n";
        $config .= "        'user' => " . var_export($s1UserOut, true) . ",\n";
        $config .= "        'pass' => " . var_export($s1PassOut, true) . ",\n";
        $config .= "    ],\n";
        $config .= "    'shard2' => [\n";
        $config .= "        'host' => " . var_export($shard2Host, true) . ",\n";
        $config .= "        'name' => " . var_export($shard2Name, true) . ",\n";
        $config .= "        'user' => " . var_export($s2UserOut, true) . ",\n";
        $config .= "        'pass' => " . var_export($s2PassOut, true) . ",\n";
        $config .= "    ],\n";
        $config .= "];\n\n";
        $config .= "\$hiddenhash     = " . var_export($hiddenHash, true) . ";\n";
        $config .= "\$app_secret     = " . var_export($appSecret, true) . ";\n\n";
        $config .= "\$files_location = " . var_export($filesLoc, true) . ";\n\n";
        $config .= "\$smtp_host      = " . var_export($smtpHost, true) . ";\n";
        $config .= "\$smtp_port      = " . var_export($smtpPort, true) . ";\n";
        $config .= "\$smtp_user      = " . var_export($smtpUser, true) . ";\n";
        $config .= "\$smtp_pass      = " . var_export($smtpPass, true) . ";\n";
        $config .= "\$mail_from      = " . var_export($mailFrom, true) . ";\n";
        $config .= "\$mail_from_name = " . var_export($mailFromName, true) . ";\n\n";
        $config .= "// OAuth (fill in later from admin panel or edit this file)\n";
        $config .= "\$google_client_id     = '';\n";
        $config .= "\$google_client_secret = '';\n";
        $config .= "\$github_client_id     = '';\n";
        $config .= "\$github_client_secret = '';\n";
        $config .= "\$facebook_app_id      = '';\n";
        $config .= "\$facebook_app_secret  = '';\n\n";
        $config .= "\$grecaptcha_key    = '';\n";
        $config .= "\$grecaptcha_secret = '';\n\n";
        $config .= "\$stripe_secret_key = '';\n";
        $config .= "\$stripe_public_key = '';\n\n";
        $config .= "\$vapid_subject     = '';\n";
        $config .= "\$vapid_public_key  = '';\n";
        $config .= "\$vapid_private_key = '';\n";

        if (file_put_contents($configPath, $config) !== false) {
            $success = true;
            // Lock down install directory so it can't be accessed again
            @chmod(__DIR__ . '/index.php', 0000);
            @chmod(__DIR__ . '/.htaccess', 0000);
            @chmod(__DIR__, 0000);
        } else {
            $errors[] = 'Could not write config/config.php. Check directory permissions.';
        }
    }
}

// Prefill values on error
$v = [
    'db_host'        => $_POST['db_host'] ?? 'localhost',
    'db_name'        => $_POST['db_name'] ?? '',
    'db_user'        => $_POST['db_user'] ?? '',
    'db_pass'        => $_POST['db_pass'] ?? '',
    'shard1_host'    => $_POST['shard1_host'] ?? 'localhost',
    'shard1_name'    => $_POST['shard1_name'] ?? '',
    'shard1_user'    => $_POST['shard1_user'] ?? '',
    'shard1_pass'    => $_POST['shard1_pass'] ?? '',
    'shard2_host'    => $_POST['shard2_host'] ?? 'localhost',
    'shard2_name'    => $_POST['shard2_name'] ?? '',
    'shard2_user'    => $_POST['shard2_user'] ?? '',
    'shard2_pass'    => $_POST['shard2_pass'] ?? '',
    'files_location' => $_POST['files_location'] ?? '',
    'smtp_host'      => $_POST['smtp_host'] ?? '',
    'smtp_port'      => $_POST['smtp_port'] ?? '587',
    'smtp_user'      => $_POST['smtp_user'] ?? '',
    'smtp_pass'      => $_POST['smtp_pass'] ?? '',
    'mail_from'      => $_POST['mail_from'] ?? '',
    'mail_from_name' => $_POST['mail_from_name'] ?? 'Admin',
];
function e($s) { return htmlspecialchars($s, ENT_QUOTES, 'UTF-8'); }
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Install — Wave Networks Core</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 640px; margin: 40px auto; padding: 0 20px; color: #333; background: #f8f9fa; }
        h1 { color: #2c3e50; margin-bottom: 8px; }
        h2 { color: #34495e; margin: 24px 0 12px; font-size: 1.1em; border-bottom: 2px solid #3498db; padding-bottom: 4px; }
        p.sub { color: #666; margin-bottom: 20px; }
        .error { background: #fde8e8; border: 1px solid #e74c3c; color: #c0392b; padding: 12px; border-radius: 6px; margin-bottom: 16px; }
        .error li { margin-left: 16px; }
        .success { background: #e8fde8; border: 1px solid #27ae60; color: #1e8449; padding: 16px; border-radius: 6px; }
        .success h2 { color: #1e8449; border: none; margin: 0 0 8px; }
        .warn { background: #fff3cd; border: 1px solid #ffc107; padding: 12px; border-radius: 6px; margin-top: 12px; color: #856404; }
        label { display: block; margin: 10px 0 4px; font-weight: 600; font-size: 0.9em; }
        input[type="text"], input[type="password"], input[type="number"] {
            width: 100%; padding: 8px 10px; border: 1px solid #ccc; border-radius: 4px; font-size: 0.95em;
        }
        input:focus { outline: none; border-color: #3498db; box-shadow: 0 0 0 2px rgba(52,152,219,0.2); }
        .hint { font-size: 0.8em; color: #888; margin-top: 2px; }
        .row { display: flex; gap: 12px; }
        .row > div { flex: 1; }
        button { background: #3498db; color: #fff; border: none; padding: 12px 32px; border-radius: 6px; font-size: 1em; cursor: pointer; margin-top: 24px; }
        button:hover { background: #2980b9; }
        fieldset { border: 1px solid #ddd; border-radius: 6px; padding: 12px 16px; margin-bottom: 8px; background: #fff; }
        legend { font-weight: 600; color: #2c3e50; padding: 0 6px; }
    </style>
</head>
<body>

<?php if ($success) { ?>
<div class="success">
    <h2>Installation Complete</h2>
    <p><code>config/config.php</code> has been created. Secrets have been auto-generated.</p>
    <p>Migrations will run automatically on first page load.</p>
    <p><a href="../auth/login.php">Go to login page</a></p>
</div>
<div class="warn">
    The install directory has been locked down (permissions removed).
</div>
<?php } else { ?>

<h1>Wave Networks Core — Install</h1>
<p class="sub">Fill in your database credentials. All connections will be tested before saving.</p>

<?php if (!empty($errors)) { ?>
<div class="error">
    <ul>
    <?php foreach ($errors as $err) { ?>
        <li><?= e($err) ?></li>
    <?php } ?>
    </ul>
</div>
<?php } ?>

<form method="post">

    <h2>Main Database</h2>
    <fieldset>
        <legend>wncore_main</legend>
        <div class="row">
            <div>
                <label>Host</label>
                <input type="text" name="db_host" value="<?= e($v['db_host']) ?>">
            </div>
            <div>
                <label>Database Name</label>
                <input type="text" name="db_name" value="<?= e($v['db_name']) ?>" required>
            </div>
        </div>
        <div class="row">
            <div>
                <label>Username</label>
                <input type="text" name="db_user" value="<?= e($v['db_user']) ?>" required>
            </div>
            <div>
                <label>Password</label>
                <input type="password" name="db_pass" value="<?= e($v['db_pass']) ?>">
            </div>
        </div>
    </fieldset>

    <h2>Shard Databases</h2>
    <p class="hint">If shard user/pass are blank, the main DB credentials are used.</p>

    <fieldset>
        <legend>Shard 1</legend>
        <div class="row">
            <div>
                <label>Host</label>
                <input type="text" name="shard1_host" value="<?= e($v['shard1_host']) ?>">
            </div>
            <div>
                <label>Database Name</label>
                <input type="text" name="shard1_name" value="<?= e($v['shard1_name']) ?>" required>
            </div>
        </div>
        <div class="row">
            <div>
                <label>Username</label>
                <input type="text" name="shard1_user" value="<?= e($v['shard1_user']) ?>" placeholder="(same as main)">
            </div>
            <div>
                <label>Password</label>
                <input type="password" name="shard1_pass" value="<?= e($v['shard1_pass']) ?>" placeholder="(same as main)">
            </div>
        </div>
    </fieldset>

    <fieldset>
        <legend>Shard 2</legend>
        <div class="row">
            <div>
                <label>Host</label>
                <input type="text" name="shard2_host" value="<?= e($v['shard2_host']) ?>">
            </div>
            <div>
                <label>Database Name</label>
                <input type="text" name="shard2_name" value="<?= e($v['shard2_name']) ?>" required>
            </div>
        </div>
        <div class="row">
            <div>
                <label>Username</label>
                <input type="text" name="shard2_user" value="<?= e($v['shard2_user']) ?>" placeholder="(same as main)">
            </div>
            <div>
                <label>Password</label>
                <input type="password" name="shard2_pass" value="<?= e($v['shard2_pass']) ?>" placeholder="(same as main)">
            </div>
        </div>
    </fieldset>

    <h2>File Storage</h2>
    <label>Files Directory (absolute path)</label>
    <input type="text" name="files_location" value="<?= e($v['files_location']) ?>" required placeholder="/home/username/files/">
    <p class="hint">Must be outside public_html. The directory will be created if it doesn't exist.</p>

    <h2>Email (SMTP)</h2>
    <fieldset>
        <legend>Optional — configure later in admin panel</legend>
        <div class="row">
            <div>
                <label>SMTP Host</label>
                <input type="text" name="smtp_host" value="<?= e($v['smtp_host']) ?>">
            </div>
            <div>
                <label>Port</label>
                <input type="number" name="smtp_port" value="<?= e($v['smtp_port']) ?>">
            </div>
        </div>
        <div class="row">
            <div>
                <label>SMTP Username</label>
                <input type="text" name="smtp_user" value="<?= e($v['smtp_user']) ?>">
            </div>
            <div>
                <label>SMTP Password</label>
                <input type="password" name="smtp_pass" value="<?= e($v['smtp_pass']) ?>">
            </div>
        </div>
        <div class="row">
            <div>
                <label>From Address</label>
                <input type="text" name="mail_from" value="<?= e($v['mail_from']) ?>" placeholder="noreply@yourdomain.com">
            </div>
            <div>
                <label>From Name</label>
                <input type="text" name="mail_from_name" value="<?= e($v['mail_from_name']) ?>">
            </div>
        </div>
    </fieldset>

    <button type="submit">Test Connections &amp; Install</button>
</form>

<?php } ?>

</body>
</html>
